### ISSUE TITLE
Error: Unable to load auth plugin "/var/lib/mosquitto/auth_plugin_pyauth.so".

### ISSUE THREAD

**Issue by mrshah2** [mbachry/mosquitto_pyauth#1]
OS: RHEL 7
1. I downloaded the source code for mosquitto-1.3.5, compiled it and installed it.
2. I unzipped the master.zip in the root of mosquitto-1.3.5 source and compiled it.
3. Copied the auth_plugin_pyauth.so to /var/lib/mosquitto/
4. My mosquitto.conf file is as under
   auth_plugin /var/lib/mosquitto/auth_plugin_pyauth.so
   auth_opt_pyauth_module ldap_module
   pid_file /var/run/mosquitto.pid
   persistence true
   persistence_location /var/lib/mosquitto/
   log_dest file /var/log/mosquitto/mosquitto.log
   include_dir /etc/mosquitto/conf.d
5. When I run 'mosquitto -c /etc/mosquitto/mosquitto.conf', I get the following log message:
   1413263463: mosquitto version 1.3.5 (build date 2014-10-14 01:01:00-0400) starting
   1413263463: Config loaded from /etc/mosquitto/mosquitto.conf.
   1413263463: Error: Unable to load auth plugin "/var/lib/mosquitto/auth_plugin_pyauth.so".

**Comment by ndorigatti** [comment]
Hello, i Have the same problem on Ubuntu 14.04 x86 (/usr/lib64 does not exist obviously).

I have the libmosquitto.so and libmosquitto.so.1 in that path but when i start the broker i get:
1430988994: mosquitto version 1.4.1 (build date 2015-04-03 07:41:31+0000) starting
1430988994: Config loaded from /etc/mosquitto/zito.conf.
1430988994: Error: Unable to load auth plugin "/var/lib/mosquitto/auth_plugin_pyauth.so".
1430988994: Load error: /var/lib/mosquitto/auth_plugin_pyauth.so: undefined symbol: mosquitto_topic_matches_sub

as the log, mosquitto is 1.4.1 and so plugin was built using 1.4.1 sources.
One thing to mention is that i've installed mosquitto from ppa repo, so i did not compile it manually.

**Comment by ndorigatti** [comment]
managed to fix it.
I had to modify the Makefile adding:
*-I ‘/path/to/mosquitto-1.4.1/src‘* to the CFLAGS param, and:
*-lmosquitto* to the LIBS param

then put the "mosquitto_pyauth" folder inside root of "mosquitto-1.4.1 sources" (not the src folder!) and do *make*
if you get errors about *-lmosquitto* not found it is because you have no symlink for the library (you have libmosquitto.so.1 but not libmosquitto.so)
so just do:
*ln -s /usr/lib/libmosquitto.so.1 /usr/lib/libmosquitto.so*
and launch make again, this time it will work and you'll have your auth_plugin_pyauth.so compiled correctly!

To @mbachry do you think this is worth to add to the "compiling" section?

**Comment by DxrMorgan** [comment]
in mosquitto.conf make:

auth_plugin /usr/local/lib/mosquitto/auth_plugin_pyauth.so
auth_opt_pyauth_module mosquitto_auth

EXPORT pythonpath:

export PYTHONPATH=/usr/lib/mosquitto

and run

mosquitto -c /etc/mosquitto/mosquitto.conf

1561325989: mosquitto version 1.6.3 starting
1561325989: Config loaded from /etc/mosquitto/mosquitto.conf.
1561325989: Loading plugin: /usr/local/lib/mosquitto/auth_plugin_pyauth.so
1561325989: ├── Username/password checking enabled.
1561325989: ├── TLS-PSK checking enabled.
1561325989: └── Extended authentication not enabled.
1561325989: Opening ipv4 listen socket on port 8883.
1561325989: Opening ipv6 listen socket on port 8883.
